version: '3.9'

services:
  app:
    build: .
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
      
  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
